version: "3.9"
services:
  voice-api: 
    build: 
      context: ./fastapi
      dockerfile: Dockerfile.m1
    ports: 
      - "9000:9000"
      - "8000:8000"
      - "80:80"
      - "443:443"
    platform: linux/x86_64
