region: ap-northeast-1
cluster: prod-giganoto-kisei-cluster
service: prod-giganoto-kisei-service
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://{{ env "TFSTATE_S3_BUCKET_NAME" "" }}/{{ env "TFSTATE_S3_BUCKET_KEY" "" }}
